# Generated by Django 4.1.7 on 2023-07-17 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
    ]
