# Generated by Django 4.1.7 on 2023-06-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_post_marka_remove_post_type_post_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
