# Generated by Django 4.1.7 on 2023-06-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_photos1_post_photos2_post_photos3_post_photos4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photos4',
        ),
        migrations.AddField(
            model_name='post',
            name='photos5',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
