# Generated by Django 4.1.7 on 2023-06-28 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='car', on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
