# Generated by Django 4.1.7 on 2023-07-16 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_post_photos2_post_photos3_post_photos4_post_photos5_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=10),
        ),
    ]
